### PR TITLE
Require the dest argument to the junos_cli module.

### PR DESCRIPTION
**Pull request by stacywsmith**
Addresses #190.

### CODE REVIEW

**Comment by stacywsmith** [comment]
@dgarros Can you please take a look at this?

**Comment by dgarros** [comment]
Hi @stacywsmith 
There are some commands that return nothing hence I don't think we should make `dest` mandatory.
have you found an issue because dest was missing ?

**Comment by stacywsmith** [comment]
@dgarros Yes, if dest is not specified an AttributeError exception is raised. Please see the discussion on #190.

**Comment by dgarros** [comment]
got it, in this case we should handle the exception properly or check if `dest` is defined.   
I'll give it a try quickly

**Comment by stacywsmith** [comment]
@dgarros The issue is [here](https://github.com/Juniper/ansible-junos-stdlib/blob/master/library/junos_cli#L184). We attempt to open the file specified by `dest` even if the value is `None`. I think you can simply wrap this block in an if:
```
        if dest is not None:
            with open(args['dest'], 'w') as outputfile:
                if args['format'] == 'text':
                    outputfile.write(cli_output)
                elif args['format'] == 'xml':
                    outputfile.write(etree.tostring(cli_output))
```

We also need to clean up the conflicting documentation which says the `dest` argument is required.

**Comment by stacywsmith** [comment]
Handled by #193.

**Pull request closed without merging**
