### PR TITLE
Restructure action_plugins implementation to fix issue in ansible==2.9

### PR DESCRIPTION
**Pull request by rsmekala**
Fixes issue #465.

### Changes
- Move ActionModule implemetaion from `module_utils/juniper_junos_common.py` to `action_plugins/juniper_junos_common_action.py`
- Dropped support for `Juniper.junos==1.4.3` module naming e.g `junos_get_facts`, `junos_get_config`.
- Replaced `convert_to_bool_func` with Ansible's implemetaion of `boolean`.

### CODE REVIEW

**Comment by rsmekala** [comment]
@vnitinv Updated the code as discussed offline.

**Comment by vnitinv** [comment]
@rsmekala Can you add UT result here?

**Comment by rsmekala** [comment]
ok to test

**Comment by rsmekala** [comment]
retest this please

**Comment by rsmekala** [comment]
retest this please

**Comment by rsmekala** [comment]
@vnitinv UT is passing. Please merge the PR.

**Comment by paleblued0t** [comment]
I believe we may want to add this to handle the TypeError exception that boolean throws when the value cannot be converted. 

```python
                if allow_bool_values is True:
                    # Try to convert it to a boolean value. Will be None if it
                    # can't be converted.
                    try:
                        bool_val = boolean(v)
                    except:
                        bool_val = None
```

**Pull request merged**
