### PR TITLE
Virtual Chassis reboot fix

### PR DESCRIPTION
**Pull request by anuragmenon2011**
Proposed fix for software upgrade issues and reboot issues for virtual chassis. Kindly review and merge @vnitinv

### CODE REVIEW

**Comment by vnitinv** [comment]
@rsmekala Can you please verify this fix.

**Comment by jnpr-community-netdev** [comment]
Can one of the admins verify this patch?

**Comment by jnpr-community-netdev** [comment]
Can one of the admins verify this patch?

**Comment by rahkumar651991** [comment]
The particular part of code is now handled in junos-eznc(PyEZ) so it is not relevant here anymore. 
Closing this pull request for that reason.

**Pull request closed without merging**
