### PR TITLE
Refactored Dockerfile and cleaned up README

### PR DESCRIPTION
**Pull request by ntwrkguru**
Refactored Dockerfile and cleaned up README

### CODE REVIEW

**Comment by ntwrkguru** [comment]
The Travis tests are broken. @vnitinv

**Comment by rsmekala** [comment]
@ntwrkguru Travis tests are broken as it is unable to deploy the Junos VM. We use Ravello to deploy the VM, but since it was bought by Oracle we don't have the access to deploy the VM.

I am working on a temporary alternative for Travis.

**Comment by jnpr-community-netdev** [comment]
Can one of the admins verify this patch?

**Comment by ntwrkguru** [comment]
@vnitinv ?

**Pull request merged**
