### PR TITLE
remove requirements.txt file

### PR DESCRIPTION
**Pull request by dineshbaburam91**
Removed requirements.txt file for security reason

### CODE REVIEW

**Comment by jnpr-community-netdev** [comment]
Can one of the admins verify this patch?

**Comment by rsmekala** [comment]
Resolves #448

**Comment by rsmekala** [comment]
ok to test

**Comment by rsmekala** [comment]
@dineshbaburam91 pyez-ansible container uses requirements.txt to install all its dependencies, including ansible. So, if we remove it from requirements.txt we will have to specify the instruction in Dockerfile.

https://github.com/Juniper/ansible-junos-stdlib/blob/176e73db521cebe0a41aee78a75c239ab4f89eb6/Dockerfile#L9-L10

Please update the Dockerfile accordingly.

**Pull request merged**
