### PR TITLE
Add support for Console over SSH (finally)

### PR DESCRIPTION
**Pull request by dgarros**
After some time we are finally getting back to this topic.

This PR is adding support for Console over SSH to all modules by adding support for 2 new parameters `cs_user` and `cs_passwd`

The way the support for Console over SSH has been implemented in Pyez, the option `mode` is not really required so I was not sure if we should had something specific or not.

### CODE REVIEW

**Comment by jnpr-community-netdev** [comment]
Can one of the admins verify this patch?

**Comment by jnpr-community-netdev** [comment]
Can one of the admins verify this patch?

**Comment by vnitinv** [comment]
@rsmekala @dineshbaburam91 can we cherry-pick the changes. We don't need the changes done in requirements.tzt

**Comment by rsmekala** [comment]
@dgarros Thanks for the contribution. Merging this (finally 😄 )

**Pull request merged**
