### PR TITLE
Fix ansible lint

### PR DESCRIPTION
**Pull request by bhundven**

### CODE REVIEW

**Comment by bhundven** [comment]
```$ ansible-lint playbooks/**/*.yml
[702] Use 'galaxy_tags' rather than 'categories'
/home/users/bhundven/gitlab.com/ZonarSystems/data-infrastructure/ansible/net/roles/Juniper.junos/meta/main.yml:1
{'meta/main.yml': {'__file__': u'/home/users/bhundven/gitlab.com/ZonarSystems/data-infrastructure/ansible/net/roles/Juniper.junos/meta/main.yml', u'dependencies': [], u'galaxy_info': {u'description': u'Network build automation of Junos devices.', u'license': u'Apache 2.0', u'author': u'Juniper', u'company': u'Juniper Networks, Inc.', u'galaxy_tags': [u'networking', u'junos', u'juniper'], '__line__': 2, u'platforms': [{'__file__': u'/home/users/bhundven/gitlab.com/ZonarSystems/data-infrastructure/ansible/net/roles/Juniper.junos/meta/main.yml', u'name': u'junos', '__line__': 9, u'versions': [u'all']}], '__file__': u'/home/users/bhundven/gitlab.com/ZonarSystems/data-infrastructure/ansible/net/roles/Juniper.junos/meta/main.yml', u'categories': [u'networking'], u'min_ansible_version': 2.1}, '__line__': 1}}

[201] Trailing whitespace
/home/users/bhundven/gitlab.com/ZonarSystems/data-infrastructure/ansible/net/roles/Juniper.junos/meta/main.yml:4
  description: Network build automation of Junos devices. ```

**Comment by jnpr-community-netdev** [comment]
Can one of the admins verify this patch?

**Comment by jnpr-community-netdev** [comment]
Can one of the admins verify this patch?

**Comment by rsmekala** [comment]
ok to test

**Comment by rsmekala** [comment]
@ vnitinv `categories` has been deprecated. So it can be removed.
 
Use 'galaxy_tags' rather than 'categories'

**Comment by rsmekala** [comment]
@bhundven Thanks for this PR. Merging it.

**Pull request merged**
