### PR TITLE
adding check_mode variable to the AnsibleModule() object call for junos_config, junos_facts, junos_jsnapy and junos_table which were missing.

### PR DESCRIPTION
**Pull request by itsgc**
This solves Issue #340. As this is my first PR, apologies for anything that might be in bad form.

### CODE REVIEW

**Comment by vnitinv** [comment]
@itsgc Can you confirm which version of Ansible you are using?

**Comment by itsgc** [comment]
Hello @vnitinv this has been tested against Ansible v2.3.1.0. I will attach a full pip freeze as soon as i am on my work computer.

Best

**Comment by itsgc** [comment]
Hello @vnitinv 

Here is the content of my pip freeze. Hope this helps.
[pipfreeze.txt](https://github.com/Juniper/ansible-junos-stdlib/files/1983668/pipfreeze.txt)

Best Regards

**Comment by itsgc** [comment]
Hello @vnitinv, anything else that you need for this PR?

**Comment by vnitinv** [comment]
@itsgc We made the fix via a different approach which will have the cascading effect. Check #357 for more details.

**Pull request closed without merging**
