### PR TITLE
Fixed juniper_junos_rpc error in Python 3

### PR DESCRIPTION
**Pull request by rsmekala**
- On mentioning dest_dir for juniper_junos_rpc in Python 3 raises a TypeError, as in Python 3 strings are encoded as bytes. Fix: Add encoding schema while converting lxme.etree to string
- Added integration tests for juniper_junos_rpc for avoiding such errors in the future.

### CODE REVIEW

**Comment by vnitinv** [comment]
@rsmekala Check why test is failing.

**Comment by jnpr-community-netdev** [comment]
Can one of the admins verify this patch?

**Comment by rsmekala** [comment]
ok to test

**Comment by rsmekala** [comment]
retest this please

**Comment by rsmekala** [comment]
test this please

**Comment by rsmekala** [comment]
test this please

**Comment by rsmekala** [comment]
Closing request will cleanup unwanted changes and raise new requests.

**Pull request closed without merging**
